### ISSUE TITLE
realtime.yml file not found

### ISSUE THREAD

**Issue by meadhikari** [debrouwere/google-analytics#14]
Where do I find this file?

https://github.com/debrouwere/google-analytics/blob/master/googleanalytics/account.py#L242

**Comment by regynald** [comment]
You need to add it manually. 
Just copy realtime.yml(https://github.com/debrouwere/google-analytics/blob/master/googleanalytics/realtime.yml)
into wherever you have the package installed.

**Comment by debrouwere** [comment]
Hmmm, because I always install from source I've never come across this problem, but will try to make sure that the packaged version has this available in the proper location. Thanks for the report.
