### ISSUE TITLE
Exception on storing-credentials example

### ISSUE THREAD

**Issue by tolmun** [debrouwere/google-analytics#16]
On line where opening json file it raise "AttributeError: 'module' object has no attribute 'parse'".
https://github.com/debrouwere/google-analytics/wiki/Authentication#storing-credentials

Posible solution supporting python 2 and 3
```python
    import os
    import sys

    if os.path.exists(CREDENTIAL_FILE):
        # credentials = json.parse(open(CREDENTIAL_FILE))
        if sys.version_info[:2] >= (3, 0):
            credentials = json.load(open(CREDENTIAL_FILE))
        else:
            credentials = json.load(file(CREDENTIAL_FILE))
```

**Comment by debrouwere** [comment]
Thanks, fixed!

**Comment by debrouwere** [comment]
(Also, Python 3 uses `open` just like Python 2 does.)
