### ISSUE TITLE
TypeError: 'CoreQuery' object is not callable

### ISSUE THREAD

**Issue by amigcamel** [debrouwere/google-analytics#19]
I tried the followings

    profile = accounts[0].webproperties[0].profile
    pageviews = profile.core.query('pageviews').range('yesterday').value

but I got

    TypeError: 'CoreQuery' object is not callable

Can someone help please?

**Comment by debrouwere** [comment]
Try this instead:

```python
profile = accounts[0].webproperties[0].profile
pageviews = profile.core.query.metrics('pageviews').range('yesterday').value
```

The API was changed recently, and `core.query` is now just a base query object, rather than a method that constructs such an object. I see I haven't updated the README to reflect this, I'll do that now.
