### ISSUE TITLE
Avoid sampling by querying by day

### ISSUE THREAD

**Issue by dhirsch** [debrouwere/google-analytics#25]
One way to avoid having Google Analytics report sampled data in certain reports is to break the report into multiple small reports (usually by day). An example can be found on the rga package (for R) at https://github.com/skardhamar/rga (see the bottom of the readme). 

Could something similar be implemented in this package?

**Comment by debrouwere** [comment]
It could be implemented in the package, but considering that it's a bit of a hack, I'd suggest you just loop through the dates you're interested in and run a separate query for each day. The correct way to do it is to ask for a report with higher precision, cf. https://github.com/debrouwere/google-analytics/wiki/Querying#precision-and-sampled-reports. Also, I don't know your specific use case of course, but people are often scared of sampled data for no good reason. Sampled data is usually plenty accurate.
