### ISSUE TITLE
Storing credentials not in keychain for command line

### ISSUE THREAD

**Issue by glitchtracker** [debrouwere/google-analytics#32]
Hi,

I need to rune your excellent tool from the command line, but from a non gui user account, which has no default keychain (and which I can't create). Is there another way, from the command line to store the token ?

Thanks

**Comment by debrouwere** [comment]
Sure, store `GOOGLE_ANALYTICS_CLIENT_ID`, `GOOGLE_ANALYTICS_CLIENT_SECRET` and `GOOGLE_ANALYTICS_REFRESH_TOKEN` in environment variables instead.

**Comment by glitchtracker** [comment]
Hi,
Thanks, but how to get the token and put it in the variable.
Could you give a command line example ?
I'm a newbie
Thanks

**Comment by debrouwere** [comment]
You will have to get the refresh token interactively, there is no way around it. If you can't, it's better to use a service account, though unfortunately that functionality is not 100% stable yet.

**Comment by glitchtracker** [comment]
Thanks I know that I need to get it interactively, but your utility triggers it, and then stores the token in the keychain, and cleverly refreshes it.
I don't know were the token is when the interactive process produces it, therefore I can't get it, and hence can't populate the variable with it. So I miss the part about grabbing the token.
Also, will you command line utility, be able to see the token in the variable and then refresh it, and put it back in the var, like it does with the keychain.

**Comment by debrouwere** [comment]
It's a bit wonky but `ga --identity my_identity --account my_account --webproperty my_webproperty authorize --output kv` should get you what you need. Also, refresh tokens generally stay valid unless revoked. As you say, they work by exchanging a refresh token for a temporary token for each session, but this will happen regardless of how you authenticate.

**Comment by debrouwere** [comment]
I see there's some things in the documentation as well as in the CLI that could use improvement, but the issue tracker isn't really the place for support, so closing for now. Thanks for the input, though.
