### ISSUE TITLE
Google Analytics Sampling 

### ISSUE THREAD

**Issue by ChamRoshi** [debrouwere/google-analytics#35]
From the few days I've spent reading through this project, I can't see whether there's any method to either detect whether sampling is going on in the returned report and the degree of sampling. 

[This article](http://code.markedmondson.me/anti-sampling-google-analytics-api/) sets out in psudocode how to implement the anti-sampling and I'd be interested in helping... if only I could see where we can access the `sampleReadCounts`.

**Comment by debrouwere** [comment]
The standard errors of sampled data are mostly small, so this doesn't bother me. However, I know some other users are interested in this functionality so if you can come up with a clean implementation, I'd be happy to merge it.
