### ISSUE TITLE
Python 3 support?

### ISSUE THREAD

**Issue by Bartvds** [debrouwere/google-analytics#9]
I was wondering if this package would work as intended under Python 3.4, as neither Github nor Pypi mention it. I only see 2.7 in travis.yml so I thought I'd ask.

**Comment by debrouwere** [comment]
The internals are mostly Python 3 ready, but one of our dependencies isn't yet: https://github.com/google/google-api-python-client So unfortunately, nope, won't work in Python 3 at this point. It would probably be possible to strip out the Google API client and just use generic oAuth code instead, but I don't need Python 3 that badly myself, so leaving things as-is for now.

**Comment by Bartvds** [comment]
google-api-python-client 1.4.0 does, it's releases just now (see https://github.com/google/google-api-python-client/issues/3#issuecomment-78173674)

**Comment by debrouwere** [comment]
Aha, good to know. Tests now pass in Python 3, though no guarantees that everything will work quite yet.
